### ISSUE TITLE
Looks like FNB changed their html again? TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by jacques** [hendrikswan/fnb-scraper#1]
```
/Users/jacques/git/fnb-scraper/index.js:296
v=transactionhistory.navigator.TransactionHistoryRedirect[^\']+\'/g)[0].replac
                                                                    ^
TypeError: Cannot read property '0' of null
    at /Users/jacques/git/fnb-scraper/fnb-scraper/index.js:296:118
    at Gunzip.<anonymous> (/Users/jacques/git/fnb-scraper/index.js:269:13)
    at Gunzip.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
```

**Comment by hendrikswan** [comment]
Probably. That code is very old though, and not terribly solid :)

**Comment by HannibalZA** [comment]
ever tried to resurrect this?

**Comment by stefvonb** [comment]
> ever tried to resurrect this?

I'm actually trying to in Python at the moment... would you be keen to try help?
